// Generated by CoffeeScript 1.10.0
var ComputedVar, NamedFunction, setType;

NamedFunction = require("NamedFunction");

setType = require("setType");

ComputedVar = NamedFunction("ComputedVar", function(config) {
  var self;
  self = {
    get: function() {
      return config.get();
    },
    set: function(newValue) {
      if (typeof config.set === "function") {
        config.set(newValue);
      }
      return newValue;
    }
  };
  return setType(self, ComputedVar);
});

module.exports = ComputedVar;
